# Generated by Django 4.2.3 on 2023-08-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100)),
                ('option_value', models.CharField(max_length=1000)),
            ],
        ),
    ]
