# Generated by Django 4.2.3 on 2023-08-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plyapp', '0003_feedbackdata_alter_queryoption_option_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=300)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
