# Generated by Django 4.2.3 on 2023-08-22 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plyapp', '0004_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='feedbackdata',
            name='Mobile',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10, message='Mobile number must be at least 10 digits.'), django.core.validators.MaxLengthValidator(13, message='Mobile number can be up to 13 digits.')]),
        ),
    ]
