# Generated by Django 4.2.3 on 2023-08-22 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plyapp', '0005_delete_login_alter_feedbackdata_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdata',
            name='Mobile',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10, message='Mobile number must be at least 10 digits.'), django.core.validators.RegexValidator(message='Mobile number must be 10 to 13 digits.', regex='^\\d{10,13}$')]),
        ),
    ]
