# Generated by Django 4.2.3 on 2023-08-22 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plyapp', '0007_alter_feedbackdata_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdata',
            name='Mobile',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')]),
        ),
    ]
