# Generated by Django 4.2.3 on 2023-08-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plyapp', '0008_alter_feedbackdata_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdata',
            name='Mobile',
            field=models.IntegerField(max_length=12),
        ),
    ]
